# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-30 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Url',
            new_name='Jeux',
        ),
    ]
