# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-30 13:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0002_auto_20170330_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomDuGenre', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomDuProprietaire', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=15)),
                ('rue', models.CharField(max_length=50)),
                ('numero', models.IntegerField()),
                ('codePostal', models.IntegerField()),
                ('commune', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='jeux',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jeux',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jeux',
            name='dureeMax',
            field=models.IntegerField(null=True, verbose_name='Dur\xe9e maximum'),
        ),
        migrations.AddField(
            model_name='jeux',
            name='dureeMin',
            field=models.IntegerField(null=True, verbose_name='Dur\xe9e minimum'),
        ),
        migrations.AddField(
            model_name='jeux',
            name='extension',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jeux',
            name='nombreDeJoueurMax',
            field=models.IntegerField(null=True, verbose_name='Nombre de joueur maximum'),
        ),
        migrations.AddField(
            model_name='jeux',
            name='nombreDeJoueurMin',
            field=models.IntegerField(null=True, verbose_name='Nombre de joueur minimum'),
        ),
        migrations.AddField(
            model_name='jeux',
            name='pretable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jeux',
            name='public',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jeux',
            name='genre',
            field=models.ManyToManyField(to='catalogue.Genre'),
        ),
        migrations.AddField(
            model_name='jeux',
            name='proprietaire',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalogue.Proprietaire'),
            preserve_default=False,
        ),
    ]
