# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-30 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_auto_20170330_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomDuType', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='jeux',
            name='typeDeJeu',
            field=models.ManyToManyField(to='catalogue.Type'),
        ),
    ]
