# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_auto_20170330_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeux',
            name='nomDuJeu',
            field=models.CharField(max_length=50, verbose_name='Nom du jeu'),
        ),
        migrations.AlterField(
            model_name='jeux',
            name='typeDeJeu',
            field=models.ManyToManyField(to='catalogue.Type', verbose_name='Type de jeu'),
        ),
    ]
