# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_auto_20170407_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='jeux',
            name='image',
            field=models.ImageField(default=1, upload_to='', verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jeux',
            name='dureeMax',
            field=models.IntegerField(null=True, verbose_name='Durée maximum'),
        ),
    ]
