# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_auto_20170407_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeux',
            name='image',
            field=models.ImageField(upload_to='photos/', verbose_name='Image'),
        ),
    ]
