# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 21:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0011_auto_20170407_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeux',
            name='image',
            field=models.ImageField(upload_to='photos_jeux/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='proprietaire',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL),
        ),
    ]
