# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 06:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0013_auto_20170413_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='avatars/', verbose_name='Image')),
                ('telephone', models.CharField(max_length=15)),
                ('rue', models.CharField(max_length=50)),
                ('numero', models.IntegerField()),
                ('codePostal', models.IntegerField()),
                ('commune', models.CharField(max_length=50)),
                ('afficheMail', models.BooleanField(default=False, verbose_name='Afficher Email')),
                ('afficheTelephone', models.BooleanField(default=False, verbose_name='Afficher téléphone')),
                ('afficheAdresse', models.BooleanField(default=False, verbose_name='Afficher adresse')),
                ('pretParDefaut', models.IntegerField(default=15, verbose_name='Durée des prêts par défaut')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='proprietaire',
            name='user',
        ),
        migrations.DeleteModel(
            name='Proprietaire',
        ),
    ]
