# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0015_auto_20170415_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jeux',
            name='image',
        ),
    ]
