# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0017_jeux_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeux',
            name='dureeDuPret',
            field=models.IntegerField(blank=True, null=True, verbose_name='Durée du prêt'),
        ),
        migrations.AlterField(
            model_name='jeux',
            name='dureeMax',
            field=models.IntegerField(blank=True, null=True, verbose_name='Durée maximum'),
        ),
        migrations.AlterField(
            model_name='jeux',
            name='dureeMin',
            field=models.IntegerField(blank=True, null=True, verbose_name='Durée minimum'),
        ),
        migrations.AlterField(
            model_name='jeux',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='jeux',
            name='nombreDeJoueurMax',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nombre de joueur maximum'),
        ),
        migrations.AlterField(
            model_name='jeux',
            name='nombreDeJoueurMin',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nombre de joueur minimum'),
        ),
    ]
