# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0018_auto_20170415_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeux',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos_jeux/', verbose_name='Image'),
        ),
    ]
