# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-12 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0019_auto_20170415_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunt',
            name='dateDeCreation',
            field=models.DateField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='dateDePret',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='dateDeRetour',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='dateDeRetourPrevue',
            field=models.DateField(),
        ),
    ]
