# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-12 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0020_auto_20170612_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunt',
            name='dateDeRetour',
            field=models.DateField(blank=True, null=True),
        ),
    ]
