# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-13 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0021_auto_20170612_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jeux',
            name='dureeMax',
        ),
        migrations.RemoveField(
            model_name='jeux',
            name='dureeMin',
        ),
        migrations.AddField(
            model_name='jeux',
            name='ageMax',
            field=models.IntegerField(blank=True, null=True, verbose_name='Age maximum'),
        ),
        migrations.AddField(
            model_name='jeux',
            name='ageMin',
            field=models.IntegerField(blank=True, null=True, verbose_name='Age minimum'),
        ),
        migrations.AddField(
            model_name='jeux',
            name='duree',
            field=models.IntegerField(blank=True, null=True, verbose_name='Durée'),
        ),
    ]
