# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-13 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0022_auto_20170613_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Public',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomDuPublic', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='jeux',
            name='public',
        ),
        migrations.AddField(
            model_name='jeux',
            name='public',
            field=models.ManyToManyField(to='catalogue.Public', verbose_name='Public'),
        ),
    ]
