# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-14 10:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0027_remove_jeux_agemax'),
    ]

    operations = [
        migrations.CreateModel(
            name='OngletsOuverts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jeu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jeu', to='catalogue.Jeux')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisateur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
