# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-14 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0029_remove_jeux_disponible'),
    ]

    operations = [
        migrations.AddField(
            model_name='jeux',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
